name = "BSplineDielectric"
uuid = "a2ecafb9-cd48-4d8b-9aa7-3586f5199c0a"
version = "2.0.0-DEV"
authors = ["stakahama <satoshi.takahama@gmail.com> and contributors"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Plots = "1.41.4"
SparseArrays = "1.12.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
