[deps]
BSplineDielectric = "a2ecafb9-cd48-4d8b-9aa7-3586f5199c0a"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
